package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type sqlFile struct {
	name string
	body string
}

func renderSQLFiles(m Manifest) []sqlFile {
	header := fmt.Sprintf("-- Generated by githubprbackfill\n-- manifest: %s\n-- formula: %s\n-- commons_commit: %s\n-- stamps: %d\n",
		m.Hash, m.FormulaVersion, m.SourceState.CommonsCommit, len(m.SyntheticRows.Stamps))
	files := []sqlFile{{name: "000_prologue.sql", body: header + "START TRANSACTION;\n"}}
	files = append(files, sqlFile{name: "010_system_rig.sql", body: renderRigRows(filterRigs(m.SyntheticRows.Rigs, systemRig))})
	files = append(files, sqlFile{name: "020_provisional_rigs.sql", body: renderRigRows(excludeRigs(m.SyntheticRows.Rigs, systemRig))})
	files = append(files, sqlFile{name: "030_wanted.sql", body: renderWantedRows(m.SyntheticRows.Wanted)})
	files = append(files, sqlFile{name: "040_completions.sql", body: renderCompletionRows(m.SyntheticRows.Completions)})
	files = append(files, sqlFile{name: "050_stamps.sql", body: renderStampRows(m.SyntheticRows.Stamps)})
	files = append(files, sqlFile{name: "090_validation_queries.sql", body: renderValidationQueries(m)})
	files = append(files, sqlFile{name: "999_commit.sql", body: "COMMIT;\n"})
	return files
}

func writeSQLFiles(outDir, combinedOut string, files []sqlFile) error {
	if outDir != "" {
		if err := os.MkdirAll(outDir, 0o755); err != nil {
			return fmt.Errorf("create SQL output dir: %w", err)
		}
		for _, f := range files {
			if err := os.WriteFile(filepath.Join(outDir, f.name), []byte(f.body), 0o644); err != nil {
				return fmt.Errorf("write %s: %w", f.name, err)
			}
		}
	}
	if combinedOut != "" {
		var combined strings.Builder
		for _, f := range files {
			combined.WriteString("-- ")
			combined.WriteString(f.name)
			combined.WriteByte('\n')
			combined.WriteString(f.body)
			if !strings.HasSuffix(f.body, "\n") {
				combined.WriteByte('\n')
			}
		}
		if err := os.WriteFile(combinedOut, []byte(combined.String()), 0o644); err != nil {
			return fmt.Errorf("write combined SQL: %w", err)
		}
	}
	return nil
}

func renderRigRows(rows []RigRow) string {
	if len(rows) == 0 {
		return "-- no rig rows\n"
	}
	var b strings.Builder
	for _, r := range rows {
		fmt.Fprintf(&b, "INSERT IGNORE INTO rigs (handle, display_name, gt_version, trust_level, rig_type, registered_at, last_seen) VALUES (%s, %s, %s, %d, %s, %s, %s);\n",
			sqlString(r.Handle), sqlString(r.DisplayName), sqlString(r.GTVersion), r.TrustLevel, sqlString(r.RigType), sqlString(r.RegisteredAt), sqlString(r.LastSeen))
	}
	return b.String()
}

func renderWantedRows(rows []WantedRow) string {
	if len(rows) == 0 {
		return "-- no wanted rows\n"
	}
	var b strings.Builder
	for _, r := range rows {
		fmt.Fprintf(&b, "INSERT IGNORE INTO wanted (id, title, description, project, type, priority, tags, posted_by, claimed_by, status, effort_level, evidence_url, created_at, updated_at) VALUES (%s, %s, %s, %s, %s, %d, %s, %s, %s, %s, %s, %s, %s, %s);\n",
			sqlString(r.ID), sqlString(r.Title), sqlString(r.Description), sqlString(r.Project), sqlString(r.Type), r.Priority, sqlJSON(r.Tags), sqlString(r.PostedBy), sqlString(r.ClaimedBy), sqlString(r.Status), sqlString(r.EffortLevel), sqlString(r.EvidenceURL), sqlString(r.CreatedAt), sqlString(r.UpdatedAt))
	}
	return b.String()
}

func renderCompletionRows(rows []CompletionRow) string {
	if len(rows) == 0 {
		return "-- no completion rows\n"
	}
	var b strings.Builder
	for _, r := range rows {
		fmt.Fprintf(&b, "INSERT IGNORE INTO completions (id, wanted_id, completed_by, evidence, validated_by, stamp_id, completed_at, validated_at) VALUES (%s, %s, %s, %s, %s, %s, %s, %s);\n",
			sqlString(r.ID), sqlString(r.WantedID), sqlString(r.CompletedBy), sqlString(r.Evidence), sqlString(r.ValidatedBy), sqlString(r.StampID), sqlString(r.CompletedAt), sqlString(r.ValidatedAt))
	}
	return b.String()
}

func renderStampRows(rows []StampRow) string {
	if len(rows) == 0 {
		return "-- no stamp rows\n"
	}
	var b strings.Builder
	for _, r := range rows {
		fmt.Fprintf(&b, "INSERT IGNORE INTO stamps (id, author, subject, valence, confidence, severity, context_id, context_type, skill_tags, message, created_at) VALUES (%s, %s, %s, %s, %.2f, %s, %s, %s, %s, %s, %s);\n",
			sqlString(r.ID), sqlString(r.Author), sqlString(r.Subject), sqlJSON(r.Valence), r.Confidence, sqlString(r.Severity), sqlString(r.ContextID), sqlString(r.ContextType), sqlJSON(r.SkillTags), sqlString(r.Message), sqlString(r.CreatedAt))
	}
	return b.String()
}

func renderValidationQueries(m Manifest) string {
	prefix := "github-pr-backfill validation"
	return fmt.Sprintf(`-- %s
SELECT COUNT(*) AS generated_wanted FROM wanted WHERE id LIKE 'w-gh-%%';
SELECT COUNT(*) AS generated_completions FROM completions WHERE id LIKE 'c-gh-%%';
SELECT COUNT(*) AS generated_stamps FROM stamps WHERE id LIKE 's-gh-%%';
SELECT s.id FROM stamps s LEFT JOIN completions c ON s.context_id = c.id WHERE s.id LIKE 's-gh-%%' AND c.id IS NULL;
SELECT c.id FROM completions c LEFT JOIN wanted w ON c.wanted_id = w.id WHERE c.id LIKE 'c-gh-%%' AND w.id IS NULL;
-- expected_wanted=%d expected_completions=%d expected_stamps=%d
`,
		prefix,
		m.ValidationExpectations.ExpectedWanted,
		m.ValidationExpectations.ExpectedCompletions,
		m.ValidationExpectations.ExpectedStamps,
	)
}

func sqlString(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

func sqlJSON(v any) string {
	data, err := json.Marshal(v)
	if err != nil {
		return "NULL"
	}
	return sqlString(string(data))
}

func filterRigs(rows []RigRow, handle string) []RigRow {
	var out []RigRow
	for _, row := range rows {
		if row.Handle == handle {
			out = append(out, row)
		}
	}
	return out
}

func excludeRigs(rows []RigRow, handle string) []RigRow {
	var out []RigRow
	for _, row := range rows {
		if row.Handle != handle {
			out = append(out, row)
		}
	}
	return out
}
