#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

REPOS_FILE="${BACKFILL_REPOS_FILE:-docs/backfills/github-stamps/repos.txt}"
COMMONS_DIR="${BACKFILL_COMMONS_DIR:-.tmp/github-pr-backfill/wl-commons}"
OUTPUT_DIR="${BACKFILL_OUTPUT_DIR:-.tmp/github-pr-backfill}"
UPSTREAM_REPO="${DOLTHUB_UPSTREAM_REPO:-hop/wl-commons}"
FORK_ORG="${DOLTHUB_FORK_ORG:-}"
FORK_REPO="${DOLTHUB_FORK_REPO:-wl-commons}"
BRANCH="${BACKFILL_BRANCH:-wl/${FORK_ORG:-local}/github-pr-backfill-$(date -u +%Y%m%d%H%M%S)}"
IDENTITY_OVERRIDES="${BACKFILL_IDENTITY_OVERRIDES:-docs/backfills/github-stamps/identity-overrides.json}"
SCORE_OVERRIDES="${BACKFILL_SCORE_OVERRIDES:-docs/backfills/github-stamps/pr-score-overrides.json}"
EXCLUDED_LOGINS="${BACKFILL_EXCLUDED_LOGINS:-docs/backfills/github-stamps/excluded-logins.json}"
PAGE_SIZE="${BACKFILL_GITHUB_PAGE_SIZE:-100}"
PARALLELISM="${BACKFILL_GITHUB_PARALLELISM:-8}"
REQUEST_DELAY="${BACKFILL_GITHUB_REQUEST_DELAY:-25ms}"
PUSH="${BACKFILL_PUSH:-0}"
CREATE_PR="${BACKFILL_CREATE_PR:-0}"

mkdir -p "$OUTPUT_DIR"

repo_args=()
while IFS= read -r repo || [[ -n "$repo" ]]; do
  repo="${repo%%#*}"
  repo="${repo//[$'\t\r\n ']}"
  [[ -z "$repo" ]] && continue
  repo_args+=(--repo "$repo")
done < "$REPOS_FILE"

if [[ ${#repo_args[@]} -eq 0 ]]; then
  echo "no repos found in $REPOS_FILE" >&2
  exit 1
fi

if [[ ! -d "$COMMONS_DIR/.dolt" ]]; then
  mkdir -p "$(dirname "$COMMONS_DIR")"
  dolt clone "https://doltremoteapi.dolthub.com/${UPSTREAM_REPO}" "$COMMONS_DIR"
fi

(
  cd "$COMMONS_DIR"
  if dolt remote | grep -qx upstream; then
    dolt checkout main
    dolt pull upstream main
  else
    dolt checkout main
    dolt pull origin main
    dolt remote add upstream "https://doltremoteapi.dolthub.com/${UPSTREAM_REPO}" || true
  fi
  if [[ -n "$FORK_ORG" ]]; then
    dolt remote remove fork >/dev/null 2>&1 || true
    dolt remote add fork "https://doltremoteapi.dolthub.com/${FORK_ORG}/${FORK_REPO}"
  fi
)

since_args=()
if [[ -n "${BACKFILL_MERGED_AFTER:-}" ]]; then
  since_args+=(--merged-after "$BACKFILL_MERGED_AFTER")
fi
if [[ -n "${BACKFILL_SINCE_DAYS:-}" ]]; then
  since_args+=(--since-days "$BACKFILL_SINCE_DAYS")
fi
if [[ -n "${BACKFILL_LIMIT_PER_REPO:-}" ]]; then
  since_args+=(--limit-per-repo "$BACKFILL_LIMIT_PER_REPO")
fi

manifest="$OUTPUT_DIR/manifest.json"
cache="$OUTPUT_DIR/github-cache.json"
combined_sql="$OUTPUT_DIR/backfill.sql"
sql_dir="$OUTPUT_DIR/sql"
pr_body="$OUTPUT_DIR/dolthub-pr-body.md"
combined_sql_path="$combined_sql"
if [[ "$combined_sql_path" != /* ]]; then
  combined_sql_path="$ROOT_DIR/$combined_sql_path"
fi

go run ./tools/githubprbackfill plan \
  --commons-dir "$COMMONS_DIR" \
  "${repo_args[@]}" \
  "${since_args[@]}" \
  --identity-overrides "$IDENTITY_OVERRIDES" \
  --score-overrides "$SCORE_OVERRIDES" \
  --excluded-logins "$EXCLUDED_LOGINS" \
  --github-cache "$cache" \
  --github-page-size "$PAGE_SIZE" \
  --github-request-delay "$REQUEST_DELAY" \
  --github-parallelism "$PARALLELISM" \
  --out "$manifest"

manifest_hash="$(jq -r '.hash' "$manifest")"
stamp_count="$(jq '.synthetic_rows.stamps | length' "$manifest")"
rig_count="$(jq '.synthetic_rows.rigs | length' "$manifest")"

if [[ "$stamp_count" == "0" ]]; then
  echo "no new GitHub PR stamps to backfill"
  exit 0
fi

rm -rf "$sql_dir"
go run ./tools/githubprbackfill render-sql \
  --manifest "$manifest" \
  --expect-hash "$manifest_hash" \
  --out-dir "$sql_dir" \
  --combined-out "$combined_sql"

go run ./tools/githubprbackfill validate \
  --manifest "$manifest" \
  --expect-hash "$manifest_hash"

(
  cd "$COMMONS_DIR"
  dolt checkout -b "$BRANCH"
  dolt sql < "$combined_sql_path"
  dolt add wanted completions stamps rigs
  dolt commit -m "Backfill GitHub PR review stamps"
)

cat > "$pr_body" <<EOF
Backfills GitHub PR review stamps generated by the checked-in Wasteland operator tooling.

- Manifest hash: \`$manifest_hash\`
- Formula: \`v1\`
- Stamps: \`$stamp_count\`
- New rigs: \`$rig_count\`
- Source repos: \`$(paste -sd, "$REPOS_FILE")\`
- Branch: \`$BRANCH\`

Reproduce with:

\`\`\`bash
BACKFILL_COMMONS_DIR=/path/to/wl-commons \\
BACKFILL_OUTPUT_DIR=.tmp/github-pr-backfill \\
BACKFILL_BRANCH=$BRANCH \\
scripts/github-pr-backfill.sh
\`\`\`
EOF

if [[ "$PUSH" == "1" ]]; then
  if [[ -z "$FORK_ORG" ]]; then
    echo "BACKFILL_PUSH=1 requires DOLTHUB_FORK_ORG" >&2
    exit 1
  fi
  (cd "$COMMONS_DIR" && dolt push fork "$BRANCH")
fi

if [[ "$CREATE_PR" == "1" ]]; then
  if [[ -z "${DOLTHUB_TOKEN:-}" || -z "$FORK_ORG" ]]; then
    echo "BACKFILL_CREATE_PR=1 requires DOLTHUB_TOKEN and DOLTHUB_FORK_ORG" >&2
    exit 1
  fi
  upstream_org="${UPSTREAM_REPO%%/*}"
  upstream_db="${UPSTREAM_REPO##*/}"
  title="Backfill GitHub PR review stamps"
  body_json="$(jq -n \
    --arg title "$title" \
    --rawfile description "$pr_body" \
    --arg forkOrg "$FORK_ORG" \
    --arg forkDb "$FORK_REPO" \
    --arg branch "$BRANCH" \
    --arg upstreamOrg "$upstream_org" \
    --arg upstreamDb "$upstream_db" \
    '{title: $title, description: $description, fromBranchOwnerName: $forkOrg, fromBranchRepoName: $forkDb, fromBranchName: $branch, toBranchOwnerName: $upstreamOrg, toBranchRepoName: $upstreamDb, toBranchName: "main"}')"
  response="$(curl -fsS \
    -H "authorization: token ${DOLTHUB_TOKEN}" \
    -H "content-type: application/json" \
    -X POST \
    -d "$body_json" \
    "https://www.dolthub.com/api/v1alpha1/${upstream_org}/${upstream_db}/pulls")"
  pr_id="$(jq -r '._id // .id // .pull_id // empty' <<<"$response")"
  if [[ -n "$pr_id" ]]; then
    echo "https://www.dolthub.com/repositories/${upstream_org}/${upstream_db}/pulls/${pr_id}"
  else
    echo "$response"
  fi
fi
